### ISSUE TITLE
Custom git.io url not working? 

### ISSUE THREAD

**Issue by skillzzjesse** [jgorset/git.io#5]
Running
```
git.io https://github.com/skillzzjesse/magister-tools --code=magister_tools
```
Returns 
```
https://git.io/vX4KY
```
**Please note that** I had already used [git.io](https://git.io) to shorten the URL before coming to the conclusion I needed to run it on the comandline to get a custom URL. 

Running the following would not work since git.io is not a github.com URL.
```
git.io https://git.io/vX4KY --code=magister_tools
```

Is this fixable?

**Comment by jgorset** [comment]
I've run into this myself, and I'm afraid it's not fixable – if you've already registered a short URL without a custom code, git.io refuses to make a new one. Sorry!

**Comment by skillzzjesse** [comment]
Weird how there's no way to take it out of the registry? Or is that just me?

**Comment by jgorset** [comment]
It's totally weird, @skillzzjesse. It's at GitHub's mercy, though, and unfortunately it is in ["maintenance mode"](https://github.com/jgorset/git.io/issues/2#issuecomment-157454410).

**Comment by drhus** [comment]
id the URL has a shorter already you can create a new one by adding backslash / to the end
ex. github `https://github.com/jgorset/git.io/issues/5` >> https://git.io/vxba7 
now you can still create vanity shortener with --code=NAME, adding a backslash to URL as `https://github.com/jgorset/git.io/issues/5/`

**Comment by edouard-lopez** [comment]
If you target a file you can **add a `?` at the end**, which leverage [query string](https://www.wikiwand.com/en/Query_string) in order to point to the same resource yet fools the URL shortener):

    https://raw.githubusercontent.com/parlr/lsf-e2e-tests/master/install.sh 
> https://git.io/fp0lK

become

    https://raw.githubusercontent.com/parlr/lsf-e2e-tests/master/install.sh?
> https://git.io/lsf-e2e

**N.B.:** I reckon you should be able to use `#` in the same way, however I didn't tried.

**Comment by friederbluemle** [comment]
The workaround with a trailing `/`, `?`, or `#` character seems to have stopped working. When sending the request, the server now responds with:

```
"https://github.com/longversion" was supposed to be shortened to "short", but "existing" already is!
```

Interestingly, the server _only_ responds with this verbose error if that trailing character has been added. Otherwise the server just responds with `201 Created` and the long version, making it _look like_ it worked, but it actually didn't. Visiting the short version redirects to a 404 on axkzer.github.io

Really unfortunate how easy it is to render a URL unusable with this service. This could happen by accident (with your own URLs), or someone could maliciously "register" any GitHub URL, making them **permanently** inaccessible by the owner.

**Comment by ahmed2m** [comment]
> The workaround with a trailing `/`, `?`, or `#` character seems to have stopped working. When sending the request, the server now responds with:
> 
> ```
> "https://github.com/longversion" was supposed to be shortened to "short", but "existing" already is!
> ```
> 
> Interestingly, the server _only_ responds with this verbose error if that trailing character has been added. Otherwise the server just responds with `201 Created` and the long version, making it _look like_ it worked, but it actually didn't. Visiting the short version redirects to a 404 on axkzer.github.io
> 
> Really unfortunate how easy it is to render a URL unusable with this service. This could happen by accident (with your own URLs), or someone could maliciously "register" any GitHub URL, making them **permanently** inaccessible by the owner.

I think someone already did that with the spam of that `axkzer` use git.io links
